// Generated from the root tracker by qa/sync-project-catalog.mjs.
// Run the generator after changing IDEAS or INIT_DONE in /index.html.
window.PORTFOLIO_CATALOG = Object.freeze([
  [
    "百应用挑战追踪器",
    "就是本页面：进度环+难度筛选+数据备份，挑战从这里开始",
    1,
    "https://jokerlixing.github.io/100apps/",
    "done"
  ],
  [
    "番茄钟计时器",
    "25分钟专注+5分钟休息，含当日专注统计",
    1,
    "https://jokerlixing.github.io/100apps/apps/002-tomato-timer/",
    "done"
  ],
  [
    "待办清单 TodoList",
    "增删改查+localStorage持久化，入门必备",
    1,
    "https://jokerlixing.github.io/100apps/apps/003-todo-list/",
    "done"
  ],
  [
    "二维码生成器",
    "输入文本/链接生成二维码，支持下载",
    1,
    "https://jokerlixing.github.io/100apps/apps/004-qr-generator/",
    "done"
  ],
  [
    "密码生成器",
    "可配长度与字符集，实时强度检测",
    1,
    "https://jokerlixing.github.io/100apps/apps/005-password-generator/",
    "done"
  ],
  [
    "单位换算器",
    "长度/重量/温度/面积多类换算",
    1,
    "https://jokerlixing.github.io/100apps/apps/006-unit-converter/",
    "done"
  ],
  [
    "倒计时日历",
    "距离目标日期还有多少天，支持多个目标",
    1,
    "https://jokerlixing.github.io/100apps/apps/007-countdown/",
    "done"
  ],
  [
    "随机点名器",
    "导入名单随机抽取，已点不重复",
    1,
    "https://jokerlixing.github.io/100apps/apps/008-random-picker/",
    "done"
  ],
  [
    "打字速度测试",
    "中英文WPM测试，统计准确率",
    1,
    "https://jokerlixing.github.io/100apps/apps/009-typing-test/",
    "done"
  ],
  [
    "记忆翻牌游戏",
    "翻牌配对小游戏，计步计时",
    1,
    "https://jokerlixing.github.io/100apps/apps/010-memory-game/",
    "done"
  ],
  [
    "电子木鱼",
    "点击敲木鱼计数，带音效禅意UI",
    1,
    "https://jokerlixing.github.io/100apps/apps/011-wooden-fish/",
    "done"
  ],
  [
    "猜数字游戏",
    "1-100猜数，二分提示太大/太小",
    1,
    "https://jokerlixing.github.io/100apps/apps/012-guess-number/",
    "done"
  ],
  [
    "节日倒计时卡片",
    "春节/国庆/生日倒计时精美卡片",
    1,
    "https://jokerlixing.github.io/100apps/apps/013-festival-countdown/",
    "done"
  ],
  [
    "BMI计算器",
    "体重身高计算+健康区间建议",
    1,
    "https://jokerlixing.github.io/100apps/apps/014-bmi-calculator/",
    "done"
  ],
  [
    "配色方案生成器",
    "随机生成和谐配色，一键复制色值",
    1,
    "https://jokerlixing.github.io/100apps/apps/015-color-palette/",
    "done"
  ],
  [
    "Markdown简历生成器",
    "表单填写实时预览，导出打印",
    1,
    "https://jokerlixing.github.io/100apps/apps/016-resume-maker/",
    "done"
  ],
  [
    "记账本",
    "分类收支记录+月度饼图统计",
    2,
    "https://jokerlixing.github.io/100apps/apps/017-expense-tracker/",
    "done"
  ],
  [
    "天气仪表盘",
    "调用天气API，温度湿度风力可视化",
    2,
    "https://jokerlixing.github.io/100apps/apps/018-weather-dashboard/",
    "done"
  ],
  [
    "贪吃蛇",
    "经典贪吃蛇，键盘操作+最高分记录",
    2,
    "https://jokerlixing.github.io/100apps/apps/019-snake-game/",
    "done"
  ],
  [
    "2048",
    "方向键合并数字，动画流畅",
    2,
    "https://jokerlixing.github.io/100apps/apps/020-2048/",
    "done"
  ],
  [
    "扫雷",
    "左键翻开右键插旗，难度三档",
    2,
    "https://jokerlixing.github.io/100apps/apps/021-minesweeper/",
    "done"
  ],
  [
    "白噪音播放器",
    "雨声/海浪/森林混合播放，助眠专注",
    2,
    "https://jokerlixing.github.io/100apps/apps/022-white-noise/",
    "done"
  ],
  [
    "番茄钟 Pro",
    "关联任务+每周专注时长图表",
    2,
    "https://jokerlixing.github.io/100apps/apps/023-pomodoro-pro/",
    "done"
  ],
  [
    "房贷计算器",
    "等额本息/等额本金对比+还款曲线图",
    2,
    "https://jokerlixing.github.io/100apps/apps/024-mortgage-calculator/",
    "done"
  ],
  [
    "汇率换算器",
    "接入实时汇率API，多币种互转",
    2,
    "https://jokerlixing.github.io/100apps/apps/025-currency-exchange/",
    "done"
  ],
  [
    "读书笔记应用",
    "书摘收藏+标签分类+搜索",
    2,
    "https://jokerlixing.github.io/100apps/apps/026-reading-notes/",
    "done"
  ],
  [
    "习惯打卡日历",
    "GitHub热力图风格的坚持记录",
    2,
    "https://jokerlixing.github.io/100apps/apps/027-habit-tracker/",
    "done"
  ],
  [
    "表情包搜索器",
    "聚合表情包搜索+收藏夹",
    2,
    "https://jokerlixing.github.io/100apps/apps/028-emoji-search/",
    "done"
  ],
  [
    "英语单词卡片",
    "翻卡记忆+艾宾浩斯复习计划",
    2,
    "https://jokerlixing.github.io/100apps/apps/029-word-cards/",
    "done"
  ],
  [
    "日历应用",
    "月视图+添加事件+今日高亮",
    2,
    "https://jokerlixing.github.io/100apps/apps/030-calendar/",
    "done"
  ],
  [
    "抽奖转盘",
    "可配置奖项与权重，转盘动画",
    2,
    "https://jokerlixing.github.io/100apps/apps/031-lucky-wheel/",
    "done"
  ],
  [
    "模拟电商列表页",
    "小满百货：商品搜索筛选+五种排序+购物车与运费计算",
    2,
    "https://jokerlixing.github.io/100apps/apps/032-simulated-shop/",
    "done"
  ],
  [
    "代码片段管理器",
    "INDEX/33：本地语法高亮+组合检索+收藏与片段CRUD",
    2,
    "https://jokerlixing.github.io/100apps/apps/033-code-snippet-manager/",
    "done"
  ],
  [
    "多任务倒计时",
    "TRACK/34：并行计时+批量控制+声光提醒与刷新恢复",
    2,
    "https://jokerlixing.github.io/100apps/apps/034-multi-countdown/",
    "done"
  ],
  [
    "随机分组工具",
    "DRAW/35：安全随机分组+成员锁定重洗+结果复制",
    2,
    "https://jokerlixing.github.io/100apps/apps/035-random-grouping/",
    "done"
  ],
  [
    "人生进度条",
    "LIFE/36：人生长尺+自然周期校准+量化目标管理",
    2,
    "https://jokerlixing.github.io/100apps/apps/036-life-progress/",
    "done"
  ],
  [
    "个人博客",
    "SIGNAL/37：Markdown写作台+全文检索+标签与月份归档",
    3,
    "https://jokerlixing.github.io/100apps/apps/037-personal-blog/",
    "done"
  ],
  [
    "在线问卷系统",
    "PULSE/38：问卷设计+URL分享填写+本地结果统计",
    3,
    "https://jokerlixing.github.io/100apps/apps/038-online-survey/",
    "done"
  ],
  [
    "短链接服务",
    "CUT/39：本地短签+Hash跳转门+七日点击统计",
    3,
    "https://jokerlixing.github.io/100apps/apps/039-short-link/",
    "done"
  ],
  [
    "图片压缩工具",
    "PRESS/40：Canvas本地批量压缩+前后预览+下载",
    3,
    "https://jokerlixing.github.io/100apps/apps/040-image-compressor/",
    "done"
  ],
  [
    "二维码名片",
    "STAMP/41：vCard电子名片+本地二维码+VCF下载",
    3,
    "https://jokerlixing.github.io/100apps/apps/041-qr-business-card/",
    "done"
  ],
  [
    "多人实时白板",
    "BOARD/42：Canvas画板+WebSocket房间同步+协作光标",
    3,
    "https://jokerlixing.github.io/100apps/apps/042-realtime-whiteboard/",
    "done"
  ],
  [
    "网页聊天室",
    "PATCH/43：WebSocket群聊+在线成员+最近历史",
    3,
    "https://jokerlixing.github.io/100apps/apps/043-web-chat/",
    "done"
  ],
  [
    "留言墙",
    "POST/44：弹幕分拣带+本地留言+点赞筛选",
    3,
    "https://jokerlixing.github.io/100apps/apps/044-message-wall/",
    "done"
  ],
  [
    "RSS阅读器",
    "DIAL/45：RSS/Atom订阅+聚合+已读追踪",
    3,
    "https://jokerlixing.github.io/100apps/apps/045-rss-reader/",
    "done"
  ],
  [
    "在线测验系统",
    "SCAN/46：本地题库组卷+限时答题+错题复盘",
    3,
    "https://jokerlixing.github.io/100apps/apps/046-online-quiz/",
    "done"
  ],
  [
    "拼图小游戏",
    "SHIFT/47：全图拖拽交换+本地图片+计时纪录",
    3,
    "https://jokerlixing.github.io/100apps/apps/047-sliding-puzzle/",
    "done"
  ],
  [
    "键盘钢琴",
    "TAPE/48：双八度演奏+磁带时间轴+录制回放",
    3,
    "https://jokerlixing.github.io/100apps/apps/048-keyboard-piano/",
    "done"
  ],
  [
    "屏幕录制工具",
    "FRAME/49：本地录屏+双路音频+暂停与下载",
    3,
    "https://jokerlixing.github.io/100apps/apps/049-screen-recorder/",
    "done"
  ],
  [
    "局域网文件快传",
    "BEAM/50：WebRTC点对点传输+二维码配对+多文件进度",
    3,
    "https://jokerlixing.github.io/100apps/apps/050-lan-file-transfer/",
    "done"
  ],
  [
    "股票自选行情",
    "TICK/51：免密行情刷新+本地自选+交互 K 线与离线降级",
    3,
    "https://jokerlixing.github.io/100apps/apps/051-stock-watchlist/",
    "done"
  ],
  [
    "在线脑图编辑器",
    "LINE/52：本地脑图编辑+分支折叠+撤销重做与 PNG 导出",
    3,
    "https://jokerlixing.github.io/100apps/apps/052-mind-map-editor/",
    "done"
  ],
  [
    "本地密码管理器",
    "LOCKBOX/53：主密码加密+本地账号库+安全生成与密文备份",
    3,
    "https://jokerlixing.github.io/100apps/apps/053-password-vault/",
    "done"
  ],
  [
    "API测试工具",
    "PORT/54：请求编排+响应检查+CORS诊断与本地安全历史",
    3,
    "https://jokerlixing.github.io/100apps/apps/054-api-tester/",
    "done"
  ],
  [
    "JSON格式化工具",
    "SPEC/55：格式压缩+精确错误定位+可搜索折叠树",
    3,
    "https://jokerlixing.github.io/100apps/apps/055-json-formatter/",
    "done"
  ],
  [
    "正则表达式测试器",
    "PATTERN/56：实时匹配高亮+捕获组检验+替换预览",
    3,
    "https://jokerlixing.github.io/100apps/apps/056-regex-tester/",
    "done"
  ],
  [
    "本地 CORS 代理",
    "RELAY/57：白名单转发+私网拦截+请求响应调试台",
    3,
    "https://jokerlixing.github.io/100apps/apps/057-cors-proxy/",
    "done"
  ],
  [
    "网页性能检测器",
    "TRACE/58：PageSpeed实时审计+核心指标+请求瀑布",
    3,
    "https://jokerlixing.github.io/100apps/apps/058-web-performance/",
    "done"
  ],
  [
    "字幕时间轴编辑器",
    "CUT/59：本地视频预览+SRT/VTT逐条校准+走片尺导出",
    3,
    "https://jokerlixing.github.io/100apps/apps/059-subtitle-editor/",
    "done"
  ],
  [
    "在线图片编辑器",
    "PRISM/60：本地裁剪+非破坏调色+文字导出",
    3,
    "https://jokerlixing.github.io/100apps/apps/060-image-editor/",
    "done"
  ],
  [
    "每日壁纸应用",
    "LUMEN/61：Bing每日图+八日胶片+收藏与固定首页",
    3,
    "https://jokerlixing.github.io/100apps/apps/061-daily-wallpaper/",
    "done"
  ],
  [
    "AI聊天助手",
    "WIRE/62：兼容接口+流式报文+本地多会话与临时密钥",
    4,
    "https://jokerlixing.github.io/100apps/apps/062-ai-chat/",
    "done"
  ],
  [
    "AI写作助手",
    "MARGIN/63：四类改写+流式BYOK+修订差异与本地历史",
    4,
    "https://jokerlixing.github.io/100apps/apps/063-ai-writer/",
    "done"
  ],
  [
    "AI识图取字",
    "GLYPH/64：本地批量OCR+中英模型+校样导出",
    4,
    "https://jokerlixing.github.io/100apps/apps/064-ai-ocr/",
    "done"
  ],
  [
    "AI语音转文字",
    "SCRIBE/65：实时听写+本地录音+逐段校对+TXT/SRT导出",
    4,
    "https://jokerlixing.github.io/100apps/apps/065-ai-transcriber/",
    "done"
  ],
  [
    "AI简历优化器",
    "PROOF/66：本地岗位匹配+成果证据诊断+可选 AI 逐条改写",
    4,
    "https://jokerlixing.github.io/100apps/apps/066-resume-optimizer/",
    "done"
  ],
  [
    "AI菜谱推荐",
    "PANTRY/67：冰箱食材匹配+三份厨房订单+缺料采购夹与可选AI增强",
    4,
    "https://jokerlixing.github.io/100apps/apps/067-ai-recipe/",
    "done"
  ],
  [
    "智能客服机器人",
    "RELAY/68：19条可编辑FAQ+意图路由+回答引用+人工接管与可选AI增强",
    4,
    "https://jokerlixing.github.io/100apps/apps/068-customer-support/",
    "done"
  ],
  [
    "AI面试模拟器",
    "PANEL/69：岗位题单+四维证据评分+追问磁带与整场复盘",
    4,
    "https://jokerlixing.github.io/100apps/apps/069-ai-interview/",
    "done"
  ],
  [
    "AI口语陪练",
    "TALKBACK/70：六类情景对练+浏览器语音+可信表达反馈+可选AI追问",
    4,
    "https://jokerlixing.github.io/100apps/apps/070-ai-speaking-coach/",
    "done"
  ],
  [
    "情绪日记",
    "TIDE/71：本地情绪潮汐+可解释趋势+自选 AI 反思",
    4,
    "https://jokerlixing.github.io/100apps/apps/071-emotion-diary/",
    "done"
  ],
  [
    "全栈电商 Demo",
    "COUNTER/72：周末市集选品+可信结算+取货码与订单履约台",
    4,
    "https://jokerlixing.github.io/100apps/apps/072-fullstack-shop/",
    "done"
  ],
  [
    "论坛社区",
    "THREADLINE/73：创作评审主题+引用回复+点赞收藏+本地/服务端身份",
    4,
    "https://jokerlixing.github.io/100apps/apps/073-forum-community/",
    "done"
  ],
  [
    "在线协同文档",
    "GALLEY/74：本机/跨设备协作+批注版本+删除房间/恢复默认稿/清空最近记录",
    4,
    "https://jokerlixing.github.io/100apps/apps/074-collaborative-document/",
    "done"
  ],
  [
    "项目管理看板",
    "RAIL/75：本地冲刺看板+成员筛选+拖拽轨道与JSON备份",
    4,
    "https://jokerlixing.github.io/100apps/apps/075-project-board/",
    "done"
  ],
  [
    "订阅管理",
    "DUE/76：本地订阅台账+30天续费票带+多币种预算提醒",
    4,
    "https://jokerlixing.github.io/100apps/apps/076-subscription-manager/",
    "done"
  ],
  [
    "短链聚合平台",
    "ROUTE/77：自定义短链+本地二维码+渠道访问统计与双模式存储",
    4,
    "https://jokerlixing.github.io/100apps/apps/077-short-link-hub/",
    "done"
  ],
  [
    "私人网盘",
    "DEPOT/78：本地文件入库+资料夹预览+分享口令+回收站与配额台账",
    4,
    "https://jokerlixing.github.io/100apps/apps/078-private-cloud/",
    "done"
  ],
  [
    "音乐播放器",
    "REEL/79：本地音频导入+多歌单管理+同步LRC与离线样带",
    4,
    "https://jokerlixing.github.io/100apps/apps/079-music-player/",
    "done"
  ],
  [
    "视频网站 Demo",
    "CHANNEL/80：三部公开片单+本地选片+定时弹幕与进度恢复",
    4,
    "https://jokerlixing.github.io/100apps/apps/080-video-site/",
    "done"
  ],
  [
    "直播弹幕系统",
    "WAVE/81：演播室级模拟直播+多轨弹幕+跨标签互动",
    4,
    "https://jokerlixing.github.io/100apps/apps/081-live-danmaku/",
    "done"
  ],
  [
    "微信小程序商城",
    "YUNXIU/82：八样山货选品+竹篮结算+本地订单与模拟微信支付",
    4,
    "https://jokerlixing.github.io/100apps/apps/082-mini-program-shop/",
    "done"
  ],
  [
    "桌面便签应用",
    "TACK/83：本地便签匣+搜索归档+Electron窗口置顶与紧凑模式",
    4,
    "https://jokerlixing.github.io/100apps/apps/083-desktop-notes/",
    "done"
  ],
  [
    "划词翻译插件",
    "MARGIN/84：网页选区批注+本地示例+在线翻译与隐私边界",
    4,
    "https://jokerlixing.github.io/100apps/apps/084-selection-translator/",
    "done"
  ],
  [
    "标签页管理插件",
    "TABLOOM/85：按网站智能分组+标签搜索+重复页清理+本地现场恢复",
    4,
    "https://jokerlixing.github.io/100apps/apps/085-tab-manager/",
    "done"
  ],
  [
    "CLI 天气工具",
    "SKY/86：免密城市查询+ASCII天气图+双语单位与JSON输出",
    5,
    "https://jokerlixing.github.io/100apps/apps/086-cli-weather/",
    "done"
  ],
  [
    "低代码表单构建器",
    "JIG/87：九类字段装配+规则校准+试填验证与独立HTML导出",
    5,
    "https://jokerlixing.github.io/100apps/apps/087-low-code-form-builder/",
    "done"
  ],
  [
    "可视化大屏编辑器",
    "GRID/88：五类图表拖拽布局+JSON/CSV字段绑定+本地预览与项目迁移",
    5,
    "https://jokerlixing.github.io/100apps/apps/088-dashboard-editor/",
    "done"
  ],
  [
    "个人知识库 Wiki",
    "LOOM/89：本地双链笔记+全文搜索+反向链接与可点击关系星图",
    5,
    "https://jokerlixing.github.io/100apps/apps/089-knowledge-wiki/",
    "done"
  ],
  [
    "自动化工作流引擎",
    "SWITCHYARD/90：触发器+条件+动作编排+本地调度审计",
    5,
    "https://jokerlixing.github.io/100apps/apps/090-workflow-engine/",
    "done"
  ],
  [
    "爬虫数据看板",
    "PULSEWATCH/91：CORS 数据源轮询+内容指纹+差异追踪与本地通知",
    5,
    "https://jokerlixing.github.io/100apps/apps/091-crawler-dashboard/",
    "done"
  ],
  [
    "简历投递助手",
    "FITROOM/92：母版资料+岗位关键词合身尺+多版本快照与打印",
    5,
    "https://jokerlixing.github.io/100apps/apps/092-resume-application-assistant/",
    "done"
  ],
  [
    "团队协作白板",
    "ROOM/93：本地协作白板+四套模板+跨标签同步与JSON/PNG导出",
    5,
    "https://jokerlixing.github.io/100apps/apps/093-collab-whiteboard/",
    "done"
  ],
  [
    "在线 IDE",
    "BENCH/94：Web沙箱预览+JavaScript Worker+Pyodide Python运行",
    5,
    "https://jokerlixing.github.io/100apps/apps/094-online-ide/",
    "done"
  ],
  [
    "AI 绘画广场",
    "MUSE/95：本地提示词生图+原创AI样片+配方画廊与PNG下载",
    5,
    "https://jokerlixing.github.io/100apps/apps/095-ai-art-gallery/",
    "done"
  ],
  [
    "语音记账",
    "TALLY/96：本地语音/文本解析+可编辑小票+月度统计与安全导出",
    5,
    "https://jokerlixing.github.io/100apps/apps/096-voice-bookkeeping/",
    "done"
  ],
  [
    "智能家居中控",
    "HABITAT/97：交互户型+10台设备模拟+四场景联动+自动化与能耗反馈",
    5,
    "https://jokerlixing.github.io/100apps/apps/097-smart-home-control/",
    "done"
  ],
  [
    "Trace/98 区块链浏览器",
    "TRACE/98：地址、交易、区块三类证据查询+关联钻取",
    5,
    "https://jokerlixing.github.io/100apps/apps/098-blockchain-explorer/",
    "done"
  ],
  [
    "Mica UI 组件库",
    "MICA/99：12个原生 Web Components+现场文档+主题令牌与可发布 npm 包",
    5,
    "https://jokerlixing.github.io/100apps/apps/099-mica-ui/",
    "done"
  ],
  [
    "个人作品集网站",
    "INDEX/100：百应用交付档案+100格项目索引+组合检索与作品清单导出",
    5,
    "https://jokerlixing.github.io/100apps/apps/100-portfolio/",
    "done"
  ]
]);
